jsm.services:
  -
    name: service1
    path: /home/java/service1/
    config-dir: config
    execution: java
    log-dir: logs
    jvm-args: "-Xms100m -Xmx1000m"
    app-args: "--spring.profiles.active=prod"
  -
    name: service2
    path: /home/java/service2/
  -
    name: service3
    path: /home/java/service3/
