jsm.services:
  service1:
    path: /home/java/service1/
    config-dir: config
    execution: java
    log-dir: logs
    jvm-args: "-Xms100m -Xmx1000m"
    app-args: "--spring.profiles.active=prod"
  service2:
    path: /home/java/service2/
  service3:
    path: /home/java/service3/
