logging:
  level:
    root: error

jsm.services:
  -
    name: service1
    path: /home/java/service1/
    execution: java
    config-dir: config
    backup-dir: backups
    jvm-args: "-Xms100m -Xmx1000m"
    app-args: "--spring.profiles.active=prod"
    log:
      output: file
      log-dir: logs
  -
    name: service1-manager
    path: /home/java/service2/
    log:
      output: stdout
      log-file-override: logs/server.log
  -
    name: service3
    path: /home/java/service3/
